import { Box } from '@marbemac/ui-primitives-react';
import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { SiteNav } from '~/components/SiteNav.tsx';
import { StyledJsxRegistry } from '@marbemac/ui-theme-next';
import { ThemedGlobal } from '@marbemac/ui-theme-next/server';

const inter = Inter({ subsets: ['latin'] });

export const runtime = 'edge';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  console.log('RootLayout.render');

  return (
    <Box as="html" lang="en" tw="min-h-screen">
      <body className={`min-h-screen flex ${inter.className}`}>
        <StyledJsxRegistry>
          <ThemedGlobal>
            <div className="w-32 border-r p-4">
              <SiteNav />
            </div>

            {children}
          </ThemedGlobal>
        </StyledJsxRegistry>
      </body>
    </Box>
  );
}

// ThemedGlobalStyle
