import './globals.css';

import { Box } from '@marbemac/ui-primitives-react';
import { StyledJsxRegistry } from '@marbemac/ui-theme-next';
import { ThemedGlobal } from '@marbemac/ui-theme-next/server';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { SiteNav } from '~/components/SiteNav.tsx';

const inter = Inter({ subsets: ['latin'] });

export const runtime = 'edge';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  console.log('RootLayout.render');

  return (
    <Box as="html" lang="en" tw="min-h-screen">
      <Box as="body" tw="flex min-h-screen" UNSAFE_class={inter.className}>
        <StyledJsxRegistry>
          <ThemedGlobal>
            <Box tw="w-32 border-r p-4">
              <SiteNav />
            </Box>

            {children}
          </ThemedGlobal>
        </StyledJsxRegistry>
      </Box>
    </Box>
  );
}
