import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { SiteNav } from '~/components/SiteNav.tsx';

const inter = Inter({ subsets: ['latin'] });

// export const runtime = 'edge';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  console.log('RootLayout.render');

  return (
    <html lang="en" className="min-h-screen">
      <body className={`min-h-screen flex ${inter.className}`}>
        <div className="w-32 border-r p-4">
          <SiteNav />
        </div>

        {children}
      </body>
    </html>
  );
}
